global:
  scrape_interval:     15s

scrape_configs:
 - job_name: money-master-api
   metrics_path: "/actuator/prometheus"
   scrape_interval: 3s
   static_configs:
    - targets: ['money-master-api-service:8080']